name: HDF5
description: HDF5 data format operations and analysis. Provides capabilities for reading, inspecting, and previewing hierarchical data stored in HDF5 format files.
server_path: src/mcp_server/server.py
