name: Pandas
description: Data manipulation and analysis using Pandas. Provides capabilities for processing CSV data, performing data analysis, and generating visualizations.
server_path: src/server.py
